version: '3.8'

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env

  # Add additional services if needed, e.g., Redis for caching or other services
